on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    services:
      image: mysql:8.0
      env:
        MYSQL_DATABASE: insvoar_test
        MYSQL_ROOT_PASSWORD: 1
      ports:
        - 3306
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Run test
        uses: go test -v ./...
  build:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Build
        run: go build -v ./...
