on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'insvoar_test'
          mysql root password: '1'
      - name: Run test
        uses: go test -v ./...
  build:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Build
        run: go build -v ./...
